routes/web.php
<?php

use App\Http\Controllers\ESController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/


Route::name('index.')
    ->controller(ESController::class)
    ->group(function () {

        Route::get('/', 'list')->name('list');
        Route::get('/create-index', 'create')->name('create');
        Route::post('/store-indexes', 'store')->name('store');
        Route::get('/search-index', 'search')->name('search');
    });

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, ValidatesRequests;
}

app/Http/Controllers/ESController.php
<?php

namespace App\Http\Controllers;

use App\Adapters\Contracts\SearchEngineContract;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;

class ESController extends Controller
{
    private SearchEngineContract $searchEngineClient;

    public function __construct(SearchEngineContract $searchEngineContract)
    {
        $this->searchEngineClient = $searchEngineContract;
    }

    /**
     * @return Application|Factory|View|\Illuminate\Foundation\Application
     */
    public function create(): \Illuminate\Foundation\Application|View|Factory|Application
    {
        return view('indices.create');
    }

    /**
     * @param Request $request
     * @return RedirectResponse
     */
    public function store(Request $request): \Illuminate\Http\RedirectResponse
    {
        try {

            $this->searchEngineClient->createIndex($request->input('index_name'));

            $this->searchEngineClient->createIndexData($request->input('index_name'), $request->input('json_data'));

            $status = [
                'successful' => 'The index created.'
            ];

        } catch (\Exception $e) {

            info($e->getMessage());

            $status = [
                'failed' => 'There is a problem. Check the log file.'
            ];
        }

        return redirect()
            ->route('index.create')
            ->with($status);
    }

    /**
     * @return View|\Illuminate\Foundation\Application|Factory|Application
     */
    public function list(): View|\Illuminate\Foundation\Application|Factory|Application
    {
        return view('indices.list', [
            'indices' => $this->searchEngineClient->list(),
        ]);
    }

    /**
     * @param Request $request
     * @return View|\Illuminate\Foundation\Application|Factory|Application
     */
    public function search(Request $request): View|\Illuminate\Foundation\Application|Factory|Application
    {
        return view('indices.search', [
            'indexName' => $request->input('index_name'),
        ]);
    }
}

app/Http/Controllers/SearchController.php
<?php

namespace App\Http\Controllers;

use App\Adapters\Contracts\SearchEngineContract;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

class SearchController
{
    /**
     * searches the value in search engine
     *
     * @param SearchEngineContract $searchEngineContract
     * @param Request $request
     * @return JsonResponse
     */
    public function __invoke(SearchEngineContract $searchEngineContract, Request $request)
    {
        $searchHits = $searchEngineContract->search(
            $request->query('q'),
            $request->query('size'),
            $request->query('index_name')
        );

        return response()->json($searchHits);
    }


}

resources/views/indices/create.blade.php
@extends('layouts/layout')

@section('content')
    <form method="post" action="{{ route('index.store') }}" class="mt-4 mx-auto w-50">
        @csrf
        <div class="form-group mb-3">
            <label for="indexName" class="form-label">Index name</label>
            <input type="text" class="form-control" id="indexName" name="index_name" placeholder="index name">
        </div>
        <div class="mb-3">
            <label for="jsonData" class="form-label">Insert index data</label>
            <textarea class="form-control" id="jsonData" name="json_data" rows="15"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Store</button>
    </form>
@endsection

resources/views/indices/list.blade.php
@extends('layouts/layout')

@section('content')
    <table class="table table-light table-bordered table-hover mt-5">
        <thead>
        <tr class="text-center">
            <th scope="col">index name</th>
            <th scope="col">index health</th>
            <th scope="col">index status</th>
            <th scope="col">docs count</th>
            <th scope="col">actions</th>
        </tr>
        </thead>
        <tbody>

        @if(!empty($indices))
            @foreach($indices as $key => $index)
                <tr class="text-center">
                    <td>{{ $index['index'] }}</td>
                    <td>{{ $index['health'] }}</td>
                    <td>{{ $index['status'] }}</td>
                    <td>{{ $index['docs.count'] }}</td>
                    <td>
                        <div class="actions">
                            <a href="{{ route('index.search', ['index_name' => $index['index']]) }}">
                                <i class="fas fa-search" style="color: #2992c7;"></i>
                            </a>
                        </div>
                    </td>
                </tr>
            @endforeach
        @endif
        </tbody>
    </table>

@endsection

resources/views/indices/search.blade.php
@extends('layouts.layout')

@section('content')

    @if($indexName)
        <h4 style="text-align: center; margin: 15px 0">
            You are searching on <span class="badge bg-info">{{ $indexName }}</span> index.
        </h4>
    @endif
    <div class="search-cloud" style="direction: rtl">
        <div class="search-part">
            <div id="search-bar" class="input-group flex-nowrap">
                <input type="text" class="form-control" placeholder="جستجو" aria-label="search"
                       aria-describedby="addon-wrapping">
            </div>
            <section id="search-results" class="">
                <div class="search-result-item sample">
                    <div class="main-text">
                    </div>
                    <div class="score">
                    </div>
                </div>

            </section>
        </div>
        <div class="cloud-part">
            <ul class="cloud" role="navigation" id="cloud" aria-label="Webdev word cloud">
                <li><a href="#" data-weight="4"></a></li>
            </ul>
        </div>
    </div>

    <script>
        $(document).ready(function () {
            $(document).on("keyup", "#search-bar input", function () {

                let query = $("#search-bar input").val();
                let index_name = window.location.href.slice(window.location.href.indexOf('?') + 1).split('&')[0].split('=')[1];

                if (query.length > 2) {
                    $.ajax({
                        method: "GET",
                        url: "/api/search?q=" + query + "&size=10" + "&index_name=" + index_name,
                        dataType: "json"
                    }).done(function (response) {

                        $("#search-results").removeClass("open");
                        $("#search-results .search-result-item:not(.sample)").remove();
                        $("#cloud").empty();

                        $.each(response.results, function (key, record) {
                            $("#search-results").append(
                                $("#search-results .search-result-item.sample:first")
                                    .clone().removeClass("sample")
                                    .find(".main-text").html(record.title).end()
                                    .find(".score").html("score: " + record._score).end()
                            )
                        });

                        $.each(response.wordcloud, function (key, word) {

                            let frequency = word.doc_count > 9 ? 9 : word.doc_count;

                            $("#cloud").append(
                                $("<li>").append(
                                    $("<a>").attr("href", "#").attr("data-weight", frequency)
                                        .text(word.key + "(" + word.doc_count + ")")
                                        .css("text-align", "center")
                                )
                            )
                        })

                        $("#search-results").addClass("open");
                    });
                } else {
                    $("#search-results").removeClass("open");
                    $("#search-results .search-result-item:not(.sample)").remove();
                    $("#cloud").empty();
                }
            })
        });
    </script>

@endsection

resources/views/layouts/layout.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>elasticsearch</title>

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&display=swap" rel="stylesheet">

    <link href="{{ asset('css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">

    <script src="https://kit.fontawesome.com/54c0875e1b.js" crossorigin="anonymous"></script>
    <script src="{{ asset("js/JQuery.js") }}"></script>

    @include('navbar')
</head>
<body>

<div class="container">

    @if(\Illuminate\Support\Facades\Session::has('successful'))
        <div class="alert alert-success alert-trim" role="alert">
            {{ \Illuminate\Support\Facades\Session::get('successful') }}
        </div>
    @elseif(\Illuminate\Support\Facades\Session::has('failed'))
        <div class="alert alert-danger alert-trim" role="alert">
            {{ \Illuminate\Support\Facades\Session::get('failed') }}
        </div>
    @endif

    @yield('content')
</div>

<script src="{{ asset('js/bootstrap.min.js') }}"></script>
</body>
</html>

resources/views/navbar.blade.php
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{{ route('index.list') }}">Index List</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('index.create') }}">Create Index</a>
                </li>
            </ul>
        </div>
    </div>
</nav>